services:
  - type: web
    name: electionwebsite
    runtime: python
    buildCommand: cd ElectionWebsite && pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn ElectionWebsite.wsgi:application --chdir ElectionWebsite --workers 1 --threads 4
