# Generated by Django 4.2.4 on 2026-02-13 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alt_name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.TextField(blank=True, default=None, null=True)),
                ('end_date', models.TextField(blank=True, default=None, null=True)),
                ('seats', models.IntegerField(default=1)),
                ('alternating', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('colour', models.CharField(max_length=7)),
                ('cScale', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uk_elections.party')),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GE', 'General Election'), ('BE', 'By-Election')], max_length=20)),
                ('date', models.DateTimeField()),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('turnout_votes', models.FloatField(blank=True, null=True)),
                ('turnout_percent', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('largest_party', models.TextField(blank=True, null=True)),
                ('prime_minister', models.TextField(blank=True, null=True)),
                ('second_party', models.TextField(blank=True, null=True)),
                ('opp_leader', models.TextField(blank=True, null=True)),
                ('map', models.CharField(blank=True, max_length=20, null=True)),
                ('hex', models.CharField(blank=True, max_length=20, null=True)),
                ('oldMP', models.CharField(blank=True, max_length=100, null=True)),
                ('constituency', models.ForeignKey(blank=True, help_text='Only for by-elections', null=True, on_delete=django.db.models.deletion.CASCADE, to='uk_elections.constituency')),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('colour', models.CharField(blank=True, max_length=7, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uk_elections.region')),
            ],
        ),
        migrations.CreateModel(
            name='ConstituencyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnout_votes', models.IntegerField(blank=True, null=True)),
                ('turnout_percent', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uk_elections.constituency')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uk_elections.election')),
            ],
        ),
        migrations.AddField(
            model_name='constituency',
            name='historic_county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historic_county', to='uk_elections.county'),
        ),
        migrations.AddField(
            model_name='constituency',
            name='modern_county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modern_county', to='uk_elections.county'),
        ),
        migrations.AddField(
            model_name='constituency',
            name='predecessors',
            field=models.ManyToManyField(blank=True, help_text='Constituencies this one was created from or replaced', related_name='successors', to='uk_elections.constituency'),
        ),
        migrations.CreateModel(
            name='Coalition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('elections', models.ManyToManyField(blank=True, to='uk_elections.election')),
                ('parties', models.ManyToManyField(blank=True, to='uk_elections.party')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(max_length=100)),
                ('votes', models.IntegerField(blank=True, null=True)),
                ('percent', models.FloatField(blank=True, null=True)),
                ('unopposed', models.BooleanField(default=False)),
                ('elected', models.BooleanField(default=False)),
                ('disqualified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uk_elections.constituency')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uk_elections.election')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uk_elections.party')),
            ],
        ),
    ]
