# Generated by Django 4.2.4 on 2023-08-23 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BYELECTION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('oldMP', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CONSTITUENCY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('originally_created', models.DateTimeField()),
                ('election_list', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ELECTION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('turnout', models.FloatField()),
                ('map', models.CharField(blank=True, max_length=20, null=True)),
                ('hex', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='REGION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PARTY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('colour', models.CharField(max_length=7)),
                ('cScale', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uk_elections.party')),
            ],
        ),
        migrations.CreateModel(
            name='GENERALTURNOUT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(blank=True, null=True)),
                ('percent', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uk_elections.constituency')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uk_elections.election')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GENERALRESULT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(max_length=100)),
                ('votes', models.IntegerField(blank=True, null=True)),
                ('percent', models.FloatField(blank=True, null=True)),
                ('unopposed', models.BooleanField(default=False)),
                ('elected', models.BooleanField(default=False)),
                ('disqualified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uk_elections.constituency')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uk_elections.election')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uk_elections.party')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ELECTIONSEATS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField()),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uk_elections.election')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uk_elections.party')),
            ],
        ),
        migrations.CreateModel(
            name='COUNTY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uk_elections.region')),
            ],
        ),
        migrations.CreateModel(
            name='CONSTSEATS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('seats', models.IntegerField()),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uk_elections.constituency')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uk_elections.election')),
            ],
        ),
        migrations.AddField(
            model_name='constituency',
            name='historic_county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historic_county', to='uk_elections.county'),
        ),
        migrations.AddField(
            model_name='constituency',
            name='modern_county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modern_county', to='uk_elections.county'),
        ),
        migrations.CreateModel(
            name='CONSTINSTANCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abolished', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abolished', to='uk_elections.election')),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uk_elections.constituency')),
                ('created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created', to='uk_elections.election')),
                ('predecessors', models.ManyToManyField(blank=True, related_name='predecessors', to='uk_elections.constituency')),
                ('successors', models.ManyToManyField(blank=True, related_name='successors', to='uk_elections.constituency')),
            ],
        ),
        migrations.CreateModel(
            name='COALITION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('elections', models.ManyToManyField(blank=True, to='uk_elections.election')),
                ('parties', models.ManyToManyField(blank=True, to='uk_elections.party')),
            ],
        ),
        migrations.CreateModel(
            name='BYTURNOUT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(blank=True, null=True)),
                ('percent', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('byelection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uk_elections.byelection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BYRESULT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(max_length=100)),
                ('votes', models.IntegerField(blank=True, null=True)),
                ('percent', models.FloatField(blank=True, null=True)),
                ('unopposed', models.BooleanField(default=False)),
                ('elected', models.BooleanField(default=False)),
                ('disqualified', models.BooleanField(default=False)),
                ('byelection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uk_elections.byelection')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uk_elections.party')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='byelection',
            name='constituency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uk_elections.constituency'),
        ),
    ]
