# Generated by Django 4.2.4 on 2023-08-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uk_elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='colour',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
