# Generated by Django 4.2.4 on 2026-02-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uk_elections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituency',
            name='historic_county',
        ),
        migrations.RemoveField(
            model_name='constituency',
            name='modern_county',
        ),
        migrations.AddField(
            model_name='constituency',
            name='historic_county',
            field=models.ManyToManyField(related_name='historic_county', to='uk_elections.county'),
        ),
        migrations.AddField(
            model_name='constituency',
            name='modern_county',
            field=models.ManyToManyField(related_name='modern_county', to='uk_elections.county'),
        ),
    ]
