# Generated by Django 4.2.4 on 2023-08-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uk_elections', '0002_county_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constinstance',
            name='predecessors',
        ),
        migrations.RemoveField(
            model_name='constinstance',
            name='successors',
        ),
        migrations.AddField(
            model_name='constinstance',
            name='predecessors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='constinstance',
            name='successors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
