# Generated by Django 4.2.4 on 2026-02-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uk_elections', '0002_remove_constituency_historic_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='constituency',
            name='start_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
