# Generated by Django 4.2.4 on 2024-06-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uk_elections', '0003_remove_constinstance_predecessors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='abolished',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='alternating',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='four_mps',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='name_changed',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='orig_preds',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='predecessors',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='prev_names',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='recreated',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='successors',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='three_mps',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='two_mps',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
