# Generated by Django 4.2.4 on 2026-02-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uk_elections', '0003_alter_constituency_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='alternating',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
    ]
