# Generated by Django 4.2.4 on 2024-06-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uk_elections', '0004_constituency_abolished_constituency_alternating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='name_changed1',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='name_changed2',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='prev_name1',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='prev_name2',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
