# Generated by Django 4.2.4 on 2026-03-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uk_elections', '0004_alter_constituency_alternating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='historic_county',
            field=models.ManyToManyField(related_name='historic_counties', to='uk_elections.county'),
        ),
        migrations.AlterField(
            model_name='constituency',
            name='modern_county',
            field=models.ManyToManyField(related_name='modern_counties', to='uk_elections.county'),
        ),
    ]
