# Generated by Django 5.2.15 on 2026-06-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uk_elections', '0005_alter_constituency_historic_county_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constituency',
            options={'verbose_name_plural': 'Constituencies'},
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name_plural': 'Counties'},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name_plural': 'Parties'},
        ),
        migrations.AddField(
            model_name='constituency',
            name='api_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
