# Generated by Django 5.2.15 on 2026-06-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uk_elections', '0006_alter_constituency_options_alter_county_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituency',
            name='api_name',
        ),
        migrations.AddField(
            model_name='constituency',
            name='api_names',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
