# Generated by Django 5.2.15 on 2026-06-19 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uk_elections', '0007_constituency_api_names_jsonfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIValidationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('updated', 'Updated'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_records', to='uk_elections.constituency')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_records', to='uk_elections.election')),
            ],
            options={
                'unique_together': {('constituency', 'election')},
            },
        ),
    ]
