# Generated by Django 5.2.15 on 2026-06-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uk_elections', '0008_api_validation_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='gj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
