# Generated by Django 5.2.15 on 2026-07-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uk_elections', '0009_election_gj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='cScale',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
