# Generated by Django 5.2.15 on 2026-07-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uk_elections', '0010_alter_party_cscale'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='alternate',
            field=models.IntegerField(default=1),
        ),
    ]
