# Generated by Django 5.2.15 on 2026-07-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uk_elections', '0011_election_alternate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='alternating',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
