# Generated by Django 5.2.15 on 2026-08-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uk_elections', '0012_alter_constituency_alternating'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateresult',
            name='winner_only',
            field=models.BooleanField(default=False),
        ),
    ]
