# Generated by Django 5.2.15 on 2026-08-07 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uk_elections', '0013_candidateresult_winner_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('link', models.URLField()),
                ('elected', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='candidateresult',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uk_elections.person'),
        ),
    ]
