# Generated by Django 5.2.15 on 2026-08-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uk_elections', '0014_person_candidateresult_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='link',
        ),
        migrations.AddField(
            model_name='person',
            name='hop_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
