# Generated by Django 5.2.15 on 2026-08-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uk_elections', '0015_remove_person_link_person_hop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='hop_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
