# Generated by Django 5.2.15 on 2026-08-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uk_elections', '0016_alter_person_hop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='hop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
